version: '3.8'

services:
  osrm-extract:
    image: osrm/osrm-backend
    container_name: osrm-extract
    volumes:
      - ./data:/data
    environment:
      - PROFILE
      - REGION  # On ajoute la région ici
    entrypoint: >
      sh -c "osrm-extract -p /opt/${PROFILE}.lua /data/${REGION}-latest-${PROFILE}.osm.pbf"

  osrm-partition:
    image: osrm/osrm-backend
    container_name: osrm-partition
    volumes:
      - ./data:/data
    depends_on:
      osrm-extract:
        condition: service_completed_successfully
    environment:
      - PROFILE
      - REGION
    entrypoint: >
      sh -c "osrm-partition /data/${REGION}-latest-${PROFILE}.osrm"

  osrm-customize:
    image: osrm/osrm-backend
    container_name: osrm-customize
    volumes:
      - ./data:/data
    depends_on:
      osrm-partition:
        condition: service_completed_successfully
    environment:
      - PROFILE
      - REGION
    entrypoint: >
      sh -c "osrm-customize /data/${REGION}-latest-${PROFILE}.osrm"
