version: '3.8'

services:
  osrm-backend-foot:
    image: osrm-backend-arm-run:latest
    container_name: osrm-backend-foot
    volumes:
      - ./data:/data
    ports:
      - "5001:5000"
    entrypoint: [ "osrm-routed", "--algorithm", "mld", "/data/provence-alpes-cote-d-azur-latest-foot.osrm" ]

  osrm-backend-bicycle:
    image: osrm-backend-arm-run:latest
    container_name: osrm-backend-bicycle
    volumes:
      - ./data:/data
    ports:
      - "5002:5000"
    entrypoint: [ "osrm-routed", "--algorithm", "mld", "/data/provence-alpes-cote-d-azur-latest-bicycle.osrm" ]
